TheRealDjmr/BG3ImprovedUI

ImprovedUI/Public/Game/GUI/Library/DataTemplates.xaml
ImprovedUI/Public/Game/GUI/StateMachine.xaml

Recreated mod effect for new version of datatemplates.xml - new version in Patch 5 hf3 that includes a new inventory tile effect, required to move inventory items around
Added picture mode to levelup screen, required layer change for this to take effect.

Patch5 hf3

---

ImprovedUI/Public/Game/GUI/Library/IUI_BackgroundIcons.xaml
ImprovedUI/Public/Game/GUI/Theme/DefaultShared.Styles.xaml

- Add Shared IUI File for Background Icons
- Include DefaultShared.Styles.xaml

Background Icon Support

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Included changes to IUI_ClassIcons.xaml for Magus class and subclasses

Update IUI_ClassIcons.xaml for Magus Icons

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Class icon for Bladesinging Wizard subclass.

Bladesinging Subclass Icon

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

added stuff for the two Resource Icons for magus (Arcane Point and Conflux Focus)
I know one of them says Arcane Pool Resource, that was made before i decided to rename it, and its kinda too much work to change everything in the mod.

Update IUI_ActionResourceIcons.xaml for Magus

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Wizard Traditions Warmagic Compatibility

---

ImprovedUI/Public/Game/GUI/Library/IUI_BackgroundIcons.xaml

Added more background icons from upcoming update to AdditionalBackgrounds mod

Update IUI_BackgroundIcons.xaml (AdditionalBackgrounds)

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

cleric blood domain

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml

There were a few entries that were excluded with past few updates.

Remainder of Bladesong action resource icons

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Added Class and Resource Icons for Wizard Traditions - Runesmith mod.
I added the same files to my mod, I'll remove them as soon as this is updated.

Wizard Traditions - Runesmith compatibility

---

Assets - Supported Mods.md
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Attempting to add Class Icon support and ActionResource icon support for [Alternate Monk](https://www.nexusmods.com/baldursgate3/mods/2266)
Apologies if I got anything wrong

Alternate Monk Subclass Icons & ActionResource Icons (for keyboard)

---

ImprovedUI/Public/Game/GUI/Library/IUI_DeityIcons.xaml

Hey, terribly sorry if there's a lot of redundant notifications from me, this is my first time making any commit on GitHub let alone this mod specifically. I saw that I'm not on the pull request list even though I thought I did that too, so trying to make sure it's all correct and in the right place. Thank you so much for all your work!

Margerard0006 patch 1

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml

Class resource icons for Mystic (Psi Points and Psionic Mastery Charges)
Keyboard only

mystic res icons (psipoints +psionicmasterycharge)

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Added Class Icons for Wielder Class Mod

Update IUI_ClassIcons.xaml Wielder Class

---

ImprovedUI/Public/Game/GUI/Library/DataTemplates.xaml
ImprovedUI/Public/Game/GUI/Library/DataTemplates_c.xaml
ImprovedUI/Public/Game/GUI/Widgets/CharacterLevelUp_c.xaml
ImprovedUI/Public/Game/GUI/Widgets/Minimap.xaml
ImprovedUI/Public/Game/GUI/Widgets/WorldTooltips.xaml

Assets, Minimap, and ShowAllItems files that need updating for Patch 4. 
Most importantly, this fixes the "Broken Inventory Controller Issue".

Additional Patch 4 Updates

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

Added Resource Icons for Wielder, please let me know if anything looks incorrect and I'll get it updated.

Update IUI_ActionResourceIcons.xaml Add Resource Icons for Wielder

---

ImprovedUI/Public/Game/GUI/Library/DataTemplates.xaml

Copies code for display amount of items in stack from Template.GameObject to Template.ItemEquipment

Update DataTemplates.xaml - Stackable Items mod compatibility

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

better star for controller ui support when there's no icon entry provided

---

ImprovedUI/Public/Game/GUI/Library/IUI_DeityIcons.xaml

gods extra

---

ImprovedUI/Public/Game/GUI/Library/CCLib_k.xaml

equipment overflow

---

ImprovedUI/Public/Game/GUI/Widgets/WorldTooltips.xaml

This should be finished, just want to test for a longer period

Showallitems v2

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Mod is currently a WIP; happy to provide a scrungly little pak for testing if confirmation is desired. 👍🏼 
---

Action resource icon for Theurgy Wizard

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Action resource icons for my mod overhaul.
Discord: redragonimmortal (ImmortalRD)

Elemental Mayhem Action Resource

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Reverts TheRealDjmr/BG3ImprovedUI#237

Revert "Add files via upload"

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Reverts TheRealDjmr/BG3ImprovedUI#238

Revert "Revert "Add files via upload""

---

ImprovedUI/Public/Game/GUI/Library/PreloadedCharacterPanel_c.xaml

stackable items controller's character inventory panel support

---

Assets - Supported Mods.md
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Hiya, 2 things in here:
- Action Resource icon support for UA7 Archfey Warlock mod (appears at level 3)
- Updating the supported mods list, as I renamed my Echo Knight mod
https://www.nexusmods.com/baldursgate3/mods/5703

UA7 Archfey Warlock icon support

---

ImprovedUI/Public/Game/GUI/Library/IUI_ClassIcons.xaml

Additions for Illrigger class mod (https://www.nexusmods.com/baldursgate3/mods/5876). Let me know if anything needs to be added/changed.

Illrigger class icons

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

Added additions for my Illrigger class mod (https://www.nexusmods.com/baldursgate3/mods/5876). Please let me know if anything needs to be altered, etc...

Illrigger Action resource icons

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

Cannot get them to show in testing. Copied the implementation of the vessel class as they are largely what I need. Not sure what I'm messing up and would appreciate a second look

Trying to make action resources show up

---

ImprovedUI/Public/Game/GUI/Library/IUI_BackgroundIcons.xaml

Background Icons for Adventurer's Guide to Tamriel: Birthsigns - beta to test with available [here](https://github.com/NellsRelo/AGtT_Birthsigns/releases/tag/0.1).

Add Background Icons for Adventurer's Guide to Tamriel - Birthsigns Mod

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml

Added ChaosPoints ActionResource

Asgorath Chaos Sorcerer Compatibility

---

ImprovedUI/Public/Game/GUI/Library/IUI_RaceIcons.xaml

Added Orc Half-Elf Subrace icon for my mod on Nexusmods.

Update IUI_RaceIcons.xaml (Orc Half-Elf)

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

Hoping to add an entry for a Resource Action icon for an upcoming mod. Not too familiar with github, so I hope I'm doing this right.

Pact Of The Shroud Action Resource

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Added lines for Illrigger class mod (https://www.nexusmods.com/baldursgate3/mods/5876). Please let me know if anything needs to be changed! Still getting used to all of this.

Update _c/_k-specific files for Illrigger class mod additions

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

4 files to support HuntersSense ActionResource in MonsterSlayer5e mod
Icons to be added to next mod release, mod version with icons attached here
[MonsterSlayer5e.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/14014657/MonsterSlayer5e.zip)

MonsterSlayer5e subclass ActionResource Icons

---

ImprovedUI/Public/Game/GUI/Library/IUI_RaceIcons.xaml

Hopefully this works, let me know if it doesn't. It's my first time really using GitHub. :')

Dryad Race Icon addition

---

ImprovedUI/Public/Game/GUI/Library/IUI_BackgroundIcons.xaml

Update IUI_BackgroundIcons.xaml for Additional Backgrounds

---

ImprovedUI/Public/Game/GUI/Library/CCLib_k.xaml

number representing CC slider value that was removed in Patch 6

---

ImprovedUI/Public/Game/GUI/Library/IUI_DeityIcons.xaml

I added icons for 2 deities, I would be very happy if you could accept a pull request, thank you.

Add Two Deities Icons

---

ImprovedUI/Public/Game/GUI/StateMachine.xaml
ImprovedUI/Public/Game/GUI/Widgets/CharacterCreation.xaml

Multiplayer in cc fix

---

ImprovedUI/Public/Game/GUI/Library/IUI_DeityIcons.xaml

I know Gods Extra added a version of [the] Raven Queen, but I'm making a mod to do so again, but different™
I did make sure to name my icon imagefile obviously differently from lostsoulman's (and very probably from any other future modder, as well).
Sorry - no file to test with (I have a repo I can share if you wanna peep it.

Update IUIDeityIcons.xaml w/ The Raven Queen

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Mod author emailed the code files directly to Djmr. I have created the branch and PR on the author's behalf and at their request.

Add "Punish" class resource icons

---

ImprovedUI/Public/Game/GUI/Library/CCLib_k.xaml

Used instrument tab as a baseline

better support for loads of passives

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml

Grid Display for Shadow Spell Slots

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml

Update IUI_ActionResourceIcons_k.xaml (Monster Slayer mod)

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

3rd time's the charm.
https://www.nexusmods.com/baldursgate3/mods/8395
Thanks!

Resource icons for GF_GhostShot and GF_Resolve

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Hi, first time making a pull. Am I doing it right? What is code?
Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
[SNEKUI.zip](https://github.com/TheRealDjmr/BG3ImprovedUI/files/15097206/SNEKUI.zip)

I made some icons for Sneak Attack Charges 

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

Action Resource Icons for Elemental Bender Class

---

ImprovedUI/Public/Game/GUI/Library/IUI_DeityIcons.xaml

add PDLoviatar as a standalone god for my unarmed loviatar cleric subclass

Cleric- Pained Domain Deity icon

---

ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_c.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceIcons_k.xaml
ImprovedUI/Public/Game/GUI/Library/IUI_ActionResourceTemplates_c.xaml

The mod isn't published on nexus yet. I've sent you a discord message with the .pak file.
Only thing I've added is support specifically for a custom action resource that I have added. Hopefully I have done this right as I don't typically use github. The custom resource is first added at barbarian level 2.

Merciless Barbarian Overhaul Support
